In [1]:
# Employee Class
class Employee:
    num_of_employees = 0

    # initializing the attributes
    def __init__(self, name, family, salary, department):
        self.name = name
        self.family = family
        self.salary = salary
        self.department = department
        Employee.num_of_employees += 1

    # Average Salary Method
    def averageSalary(self, employees):
        total_salary = sum(emp.salary for emp in employees)
        return total_salary / len(employees)

# Full Time Employee Class - Super Class
class FulltimeEmployee(Employee):
    def __init__(self, name, family, salary, department, employment_type):
        super().__init__(name, family, salary, department)
        self.employment_type = employment_type

# Instances of Employee class
employee1 = Employee("sai", "O", 50000, "data analyst")
employee2 = Employee("kumari", "Q", 80000, "developer")

# Instances of FulltimeEmployee class
fulltime1 = FulltimeEmployee("Ali", "k", 90000, "manager", "FullTime")
fulltime2 = FulltimeEmployee("sam", "r", 100000, "HR", "FullTime")
fulltime3 = FulltimeEmployee("manu", "L", 40000, "jr. software", "FullTime")

# Call member functions
employees = [employee1, employee2, fulltime1, fulltime2, fulltime3]
avgSalary = employee1.averageSalary(employees)

print("Total Employees:", Employee.num_of_employees)
print("Average Salary:", avgSalary)



Total Employees: 5
Average Salary: 72000.0


In [2]:
import numpy

random_vector = numpy.random.uniform(1, 20, 20)
print(random_vector)
print("")
print("")
reshaped_array = random_vector.reshape(4, 5)
print("")
print("")
print(reshaped_array)
reshaped_array[numpy.arange(4), numpy.argmax(reshaped_array, axis=1)] = 0
print("")
print("")
print(reshaped_array)


[16.80315758 13.1168193  18.2180487  12.50009096  9.71779387  5.46332218
  7.25887767 14.57947539  7.18358239 19.74832112 16.30509433  7.45539097
  5.87422074  3.84775234 19.27591017  8.51065893  5.89586223  9.24848341
  2.51186033 14.06072774]




[[16.80315758 13.1168193  18.2180487  12.50009096  9.71779387]
 [ 5.46332218  7.25887767 14.57947539  7.18358239 19.74832112]
 [16.30509433  7.45539097  5.87422074  3.84775234 19.27591017]
 [ 8.51065893  5.89586223  9.24848341  2.51186033 14.06072774]]


[[16.80315758 13.1168193   0.         12.50009096  9.71779387]
 [ 5.46332218  7.25887767 14.57947539  7.18358239  0.        ]
 [16.30509433  7.45539097  5.87422074  3.84775234  0.        ]
 [ 8.51065893  5.89586223  9.24848341  2.51186033  0.        ]]
