In [5]:
# Employee Class
class Employee:
    num_of_employees = 0

    # initializing the attributes
    def __init__(self, name, family, salary, department):
        self.name = name
        self.family = family
        self.salary = salary
        self.department = department
        Employee.num_of_employees += 1

    # Average Salary Method
    def averageSalary(self, employees):
        total_salary = sum(emp.salary for emp in employees)
        return total_salary / len(employees)

# Full Time Employee Class - Super Class
class FulltimeEmployee(Employee):
    def __init__(self, name, family, salary, department, employment_type):
        super().__init__(name, family, salary, department)
        self.employment_type = employment_type

# Instances of Employee class
employee1 = Employee("sai", 3, 50000, "data analyst")
employee2 = Employee("kumari", 4, 80000, "developer")

# Instances of FulltimeEmployee class
fulltime1 = FulltimeEmployee("Ali", 5, 90000, "manager", "FullTime")
fulltime2 = FulltimeEmployee("sam", 6, 100000, "HR", "FullTime")
fulltime3 = FulltimeEmployee("manu", 4, 40000, "jr. software", "FullTime")

# Call member functions
employees = [employee1, employee2, fulltime1, fulltime2, fulltime3]
avgSalary = employee1.averageSalary(employees)

print("Total Employees:", Employee.num_of_employees)
print("Average Salary:", avgSalary)



Total Employees: 5
Average Salary: 72000.0


In [6]:
import numpy

random_vector = numpy.random.uniform(1, 20, 20)
print(random_vector)
print("")
print("")
reshaped_array = random_vector.reshape(4, 5)
print("")
print("")
print(reshaped_array)
reshaped_array[numpy.arange(4), numpy.argmax(reshaped_array, axis=1)] = 0
print("")
print("")
print(reshaped_array)


[ 2.40020544  3.82502573 15.08014599 10.22644581  2.35915991 16.2519168
  1.15620555  3.54609571  7.1647101   7.00332289  8.47262328 12.041698
 15.18359167 17.54202467  7.84867571 15.45265676 14.59192852  1.98425209
 11.86621657  5.08415859]




[[ 2.40020544  3.82502573 15.08014599 10.22644581  2.35915991]
 [16.2519168   1.15620555  3.54609571  7.1647101   7.00332289]
 [ 8.47262328 12.041698   15.18359167 17.54202467  7.84867571]
 [15.45265676 14.59192852  1.98425209 11.86621657  5.08415859]]


[[ 2.40020544  3.82502573  0.         10.22644581  2.35915991]
 [ 0.          1.15620555  3.54609571  7.1647101   7.00332289]
 [ 8.47262328 12.041698   15.18359167  0.          7.84867571]
 [ 0.         14.59192852  1.98425209 11.86621657  5.08415859]]
